### ISSUE TITLE
Update to Elasticsearch 0.90.3

### ISSUE THREAD

**Issue by dadoonet** [couchbaselabs/elasticsearch-transport-couchbase#18]
Heya,

Sadly, latest version (1.1.0) is not compatible with elasticsearch 0.90.3 and upcoming versions.

```
java.lang.NoSuchMethodError: org.elasticsearch.cluster.metadata.MetaData.getIndices()Lorg/elasticsearch/common/collect/ImmutableMap;
    at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.getBucketsInPool(ElasticSearchCouchbaseBehavior.java:83)
```

It works fine with 0.90.2.

Could you update to latest elasticsearch version?

Thanks.
